name: 'Releaser'
description: 'Create a release'
inputs:
  mode: # minor/major/pre
    required: true
  prerelease:  # true/false
    required: true
runs:
  using: "composite"
  steps:
    - name: validate inputs
      shell: bash
      run: |
        python ${{ github.action_path }}
      env: |
        prerelease: ${{ inputs.prerelease }}
        mode: ${{ inputs.mode }}
    - name: Create Release
      uses: softprops/action-gh-release@v2.0.6
      with:
        draft: ${{ true }}
        prerelease: ${{ inputs.prerelease }}
        

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
