name: 'Releaser'
description: 'Create a release'
inputs:
  mode: # minor/major/pre
    required: true
  prerelease:  # true/false
    required: true
runs:
  using: "composite"
  steps:
    - name: validate inputs
      shell: bash
      run: |
        python -u "${{ github.action_path }}/src/validate_inputs.py"
      env:
        PRERELEASE: ${{ inputs.prerelease }}
        MODE: ${{ inputs.mode }}
    - name: get last release
      shell: bash
      run: |
        echo "LAST_RELEASE=$(echo python -u '${{ github.action_path }}/src/get_lase_release.py')"
        echo $LAST_RELEASE
        echo $LAST_RELEASE >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - shell: bash
      run: |
        echo $LAST_RELEASE
    - name: Create Release
      uses: softprops/action-gh-release@v2.0.6
      with:
        draft: ${{ true }}
        prerelease: ${{ inputs.prerelease }}
