name: "Releaser"
description: "Create a release"

#TODO: desriptions

inputs:
  # by conflicting inputs -> lowest priority wins
  mode: # minor/major/pre
    description: "The type of release to create"
    required: true
  prerelease: # true/false
    description: "Whether the release is a prerelease"
    required: true
  tag_format: # must include {Maj}, {Min}, {Pre} ONCE and they cannot be touching; the text enclosed by [] and including the {Pre} will only be used if it is a prerelease ( optional; excape with \\[ & \\] ).
    description: "The format of the tag"
    default: "V{Maj}.{Min}[_pre-{Pre}]"
  title_format: # can include {Maj}, {Min}, {Pre} multiple times; the text enclosed by [] and including the {Pre} will only be used if it is a prerelease ( optional; excape with \\[ & \\] )
    description: "The format of the title"
    default: "Version {Maj}.{Min}[ pre-{Pre}]"
  ignore_drafts: # true/false
    description: "Whether to ignore drafts while searching for the latest release"
    default: "true"
  reuse_old_body: # true/false; priority: 0
    description: "Whether to reuse the old release body"
    default: "true"
  body_path: # str; priority: 1
    description: "The path to the file containing the release body"
    default: ""
  body: # str; priority: 2
    description: "The release body"
    default: ""
  full_source_code_name: # str; without file extention; uses qmonnet/git-archive-all-action; feature disabled when string empty
    description: "The name of the source code"
    default: ""

runs:
  using: "composite"
  steps:
    - name: execute python script
      shell: bash
      run: |
        python -u "${{ github.action_path }}/src/releaser.py"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WORK_PATH: ${{ github.workspace }}
        REPOSITORY: ${{ github.repository }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_PRERELEASE: ${{ inputs.prerelease }}
        INPUT_TAG_FORMAT: ${{ inputs.tag_format }}
        INPUT_TITLE_FORMAT: ${{ inputs.title_format }}
        IGNORE_DRAFTS: ${{ inputs.ignore_drafts }}
        INPUT_REUSE_OLD_BODY: ${{ inputs.reuse_old_body }}
        INPUT_BODY_PATH: ${{ inputs.body_path }}
        INPUT_BODY: ${{ inputs.body }}

    - name: Git-archive-all
      uses: qmonnet/git-archive-all-action@main
      if: ${{ inputs.full_source_code_name != '' }}
      with:
        output-files: "${{ github.workspace }}/${{ inputs.full_source_code_name }}.zip"

    # - shell: bash
    #   run: |
    #     echo $s_release_tag
    #     echo $s_release_title
    #     echo $s_release_body_path

    - name: Create Release
      uses: softprops/action-gh-release@master
      with:
        draft: ${{ true }}
        prerelease: ${{ inputs.prerelease }}
        body_path: ${{ env.s_release_body_path }}
        name: ${{ env.s_release_title }}
        tag_name: ${{ env.s_release_tag }}
        make_latest: ${{ true }}

    - name: create log message
      shell: bash
      run: |
        echo "::notice title=created release::created release '${{ env.s_release_tag }}' with the title '${{ env.s_release_title }}' and prerelease: ${{ inputs.prerelease }}"
